pipeline:
  install:
    image: node:18
    commands:
      - yarn
  # lint:
  #   image: node:18
  #   commands:
  #     - yarn lint
  #     - yarn check
  build:
    image: node:18
    commands:
      - yarn build:static
  create-preview:
    image: debian
    commands:
      - |-
        apt-get update && apt-get install zip openssl curl -y
        cd build ; zip -r ../build.zip . * ; cd ..
        export RAND=`openssl rand -hex 12`
        echo $RAND
        while [ "$(curl -F "file=@build.zip" "https://preview.frsqr.xyz/upload/$RAND")" != "success" ]
        do
          echo trying...
        done
        echo
        echo "result ->"
        echo "https://preview.frsqr.xyz/$RAND/"
        rm -f build.zip
